name: Backend CI

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    branches: [ develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
    - name: Install dependencies
      working-directory: ./backend
      run: |
        uv pip install --system -e .
      
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        uv pip install flake8
        uv run flake8 app tests --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 app tests --count --max-complexity=10 --max-line-length=127 --statistics
      
    - name: Check formatting with black
      working-directory: ./backend
      run: |
        uv pip install black
        uv run black --check app tests
      
    - name: Check imports with isort
      working-directory: ./backend
      run: |
        uv pip install isort
        uv run isort --check-only --profile black app tests
      
    - name: Type check with mypy
      working-directory: ./backend
      run: |
        uv pip install mypy types-requests
        uv run mypy app
      
    - name: Test with pytest
      working-directory: ./backend
      run: |
        uv pip install pytest pytest-asyncio pytest-cov
        uv run pytest tests/ --cov=app --cov-report=xml
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        fail_ci_if_error: false 