name: Schedule Data Cleanup

on:
  schedule:
    # Run at midnight every day (UTC)
    - cron: '0 0 * * *'

  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  call-cleanup-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables based on branch
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "SUPABASE_URL=https://pstdcfittpjhxzynbdbu.supabase.co/functions/v1/cleanup-old-data" >> $GITHUB_ENV
            echo "SUPABASE_KEY=${{ secrets.PROD_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "SUPABASE_URL=https://ksuxhgigxymqoqmxekic.supabase.co/functions/v1/cleanup-old-data" >> $GITHUB_ENV
            echo "SUPABASE_KEY=${{ secrets.DEV_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          fi

      - name: Call Cleanup Edge Function
        run: |
          curl -L -X POST '${{ env.SUPABASE_URL }}' \
            -H 'Authorization: Bearer ${{ env.SUPABASE_KEY }}' \
            -H 'Content-Type: application/json'

      - name: Log completion
        if: ${{ success() }}
        run: echo "Data cleanup function executed successfully for ${{ env.ENVIRONMENT }} environment"

      - name: Log failure
        if: ${{ failure() }}
        run: echo "Failed to execute data cleanup function for ${{ env.ENVIRONMENT }} environment"
